/**
 * AI-drafted headline/subtitle/CTA for a QR design — spec section 25.
 *
 * The AI only ever proposes copy for the admin to review before anything is
 * printed; nothing here reaches a design automatically. It never touches the
 * QR code itself — that is always generated by the `qrcode` library at fixed
 * error correction, never by the model.
 */

import { getAIConfig, anthropicClient, openaiClient } from "@/lib/ai-provider"

export type DesignCopy = { headline: string; subtitle: string; cta: string; accentColor: string }

const DEFAULT_ACCENT = "#0b671c"

const SYSTEM_PROMPT = `You write short marketing copy and pick one accent colour for a printed QR sign that asks a customer to review a business. Respond with strict JSON only: {"headline":"...","subtitle":"...","cta":"...","accentColor":"#rrggbb"}. Headline: under 6 words, punchy. Subtitle: under 12 words, explains what scanning does. CTA: under 5 words, an action ("Review Us on Google", "Scan to Share Feedback"). accentColor: a single hex colour fitting the described business/style — dark enough to read as text on white (avoid pale/light colours). No markdown, no explanation, JSON only.`

export async function generateDesignCopy(prompt: string, businessName: string): Promise<DesignCopy> {
  const config = await getAIConfig()
  const userPrompt = `Business: ${businessName}\nRequest: ${prompt.slice(0, 300)}`

  let raw = ""
  if (config.provider === "anthropic") {
    const client = await anthropicClient()
    const response = await client.messages.create({
      model: config.model, max_tokens: 300,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: userPrompt }],
    })
    const block = response.content.find(b => b.type === "text")
    raw = block && block.type === "text" ? block.text : ""
  } else {
    const client = await openaiClient()
    const response = await client.chat.completions.create({
      model: config.model, max_tokens: 300,
      messages: [{ role: "system", content: SYSTEM_PROMPT }, { role: "user", content: userPrompt }],
    })
    raw = response.choices[0]?.message?.content || ""
  }

  const cleaned = raw.trim().replace(/^```(?:json)?\n?/i, "").replace(/```$/, "").trim()
  const parsed = JSON.parse(cleaned) as Partial<DesignCopy>
  const headline = String(parsed.headline || "").trim().slice(0, 60)
  const subtitle = String(parsed.subtitle || "").trim().slice(0, 120)
  const cta = String(parsed.cta || "").trim().slice(0, 40)
  const accentColor = /^#[0-9a-f]{6}$/i.test(String(parsed.accentColor || "")) ? String(parsed.accentColor) : DEFAULT_ACCENT
  if (!headline || !cta) throw new Error("AI returned incomplete design copy")
  return { headline, subtitle: subtitle || "Scan to share your feedback", cta, accentColor }
}
