import { db } from "@/lib/db"
import { Course } from "@/lib/training-types"

const TENANT_ID = "cmujurq9w005ci36afzax588l"
const FLOW_ID = "cmuli51p500aqi3rj8kepufa1"

async function main() {
  console.log("1. Clearing existing bookings for Tanfidh...")
  await db.systemSetting.upsert({
    where: { tenantId_key: { tenantId: TENANT_ID, key: "training_registrations" } },
    update: { value: JSON.stringify([]), type: "JSON", category: "TRAINING" },
    create: { tenantId: TENANT_ID, key: "training_registrations", value: JSON.stringify([]), type: "JSON", category: "TRAINING" },
  })
  console.log("✓ Cleared training_registrations to []")

  // Reset conversation states for Tanfidh
  const updatedConvs = await db.conversation.updateMany({
    where: { tenantId: TENANT_ID },
    data: { flowState: null, bookingState: null, botActive: true, automationPaused: false }
  })
  console.log(`✓ Reset ${updatedConvs.count} conversations on Tanfidh`)

  console.log("2. Seeding full 5-course catalog for Tanfidh...")
  const now = new Date().toISOString()

  const courses: Course[] = [
    {
      id: "course_bsc_certified_pro_2026",
      courseId: "BSC-2026-OM",
      tenantId: TENANT_ID,
      slug: "ai-powered-balanced-scorecard-professional",
      name: "AI-Powered Certified Balanced Scorecard Professional",
      shortTitle: "Certified BSC Professional with AI",
      category: "Strategy & Executive Leadership",
      type: "Certification",
      description: "Master contemporary corporate strategy formulation, KPI cascading, and automated performance scorecard execution powered by Generative AI analytics. Endorsed by Tanfidh Management Consultants for executive leaders, PMO directors, and performance managers across the GCC.",
      learningObjectives: [
        "Design robust 4-perspective Balanced Scorecards (Financial, Customer, Internal Process, Learning & Growth)",
        "Leverage Generative AI for real-time strategy mapping, objective alignment, and automated initiative prioritization",
        "Establish leading vs lagging Key Performance Indicators (KPIs) with mathematical thresholds and tolerance bands",
        "Cascade corporate scorecards across business units, departments, and individual performance contracts",
        "Integrate executive dashboards and automated WhatsApp alert triggers for performance exceptions"
      ],
      highlights: [
        "2 Full Days of Executive Masterclass & Hands-on Lab (08:30–16:30)",
        "Official Certificate of Completion from Tanfidh Management Consultants",
        "Complete Strategy Automation & Balanced Scorecard Toolkit with Excel/PowerBI templates",
        "Sheraton 5-Star Gourmet Lunch & Executive Networking Reception",
        "Special Offer: Pay for 1 seat and get 1 seat 100% FREE (BOGO)"
      ],
      targetAudience: [
        "Chief Executive Officers & Board Directors",
        "Strategy & Transformation Directors",
        "PMO (Project Management Office) Heads",
        "Corporate Performance & HR Leaders",
        "Government & Institutional Planners in Oman & GCC"
      ],
      prerequisites: [
        "Fundamental understanding of business management or strategy planning.",
        "Laptop recommended for AI scorecard modeling lab sessions."
      ],
      certificationDetails: "Certified Balanced Scorecard Professional Credential issued with unique digital cryptographic QR validation, verifiable globally online.",
      bannerUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=1600&auto=format&fit=crop",
      status: "PUBLISHED",
      landingPageEnabled: true,
      trainerName: "Said Al Harthi",
      trainerDesignation: "Managing Consultant & Senior Strategy Advisor",
      trainerBio: "Said Al Harthi is a veteran strategy advisor with over 20 years guiding Vision transformation across Oman and GCC ministries, sovereign funds, energy enterprises, and financial institutions.",
      trainerImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
      trainerCompany: "Tanfidh Management Consultants",
      trainerEmail: "saidalharthy@tanfidh.com",
      trainerPhone: "+968 7178 4454",
      startDate: "2026-10-13",
      endDate: "2026-10-14",
      startTime: "08:30 AM",
      endTime: "04:30 PM",
      numDays: 2,
      duration: "2 Days (08:30–16:30)",
      timezone: "Asia/Muscat (GST, UTC+4)",
      mode: "In-person",
      venueName: "Sheraton Oman Hotel",
      address: "Ruwi High Street, Financial District",
      city: "Muscat",
      country: "Sultanate of Oman",
      mapUrl: "https://maps.google.com/?q=Sheraton+Oman+Hotel+Muscat",
      maxSeats: 30,
      availableSeats: 26,
      reservedSeats: 0,
      confirmedSeats: 0,
      waitingList: 0,
      standardPrice: 500,
      currency: "OMR",
      taxPercent: 0,
      vatPercent: 5,
      paymentTerms: "Direct Bank Transfer / Wire",
      offerType: "BOGO",
      offerTitle: "Pay for 1 seat, get 1 seat FREE (Buy 1 Get 1 Free)",
      offerDescription: "Register for 1 paid delegate and bring a colleague or team member at ZERO additional cost. Includes all training materials, 5-star lunches, and two individual certificates.",
      discountAmount: 500,
      whatsappNumber: "+96871784454",
      keyword: "BSC",
      botFlowId: FLOW_ID,
      autoConfirmation: true,
      autoCertificate: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "course_strategy_pro_2026",
      courseId: "STR-2026-OM",
      tenantId: TENANT_ID,
      slug: "ai-powered-certified-strategy-professional",
      name: "AI-Powered Certified Strategy Professional",
      shortTitle: "Certified Strategy Professional with AI",
      category: "Corporate Strategy & Governance",
      type: "Certification",
      description: "Develop evidence-based strategy and leverage AI to structure market analysis, challenge assumptions, build strategic options, and lead corporate transformation initiatives across the GCC.",
      learningObjectives: [
        "Master strategic analysis frameworks (PESTEL, Porter's 5 Forces, Blue Ocean) augmented with AI synthesis",
        "Synthesize competitive intelligence and macroeconomic indicators for long-term visioning",
        "Formulate robust strategic hypotheses and test them against disruptive industry scenarios",
        "Align corporate leadership, executive stakeholders, and functional units to corporate strategic plans",
        "Build adaptive review routines and governance mechanisms for strategy realization"
      ],
      highlights: [
        "2 Full Days of Executive Strategy Masterclass (08:30–16:30)",
        "Certified Strategy Professional Credential with QR Verification",
        "Executive Strategy Blueprints & AI Framework Toolkit",
        "Sheraton 5-Star Gourmet Lunch & Executive Networking",
        "Special Offer: Pay for 1 seat and get 1 seat 100% FREE (BOGO)"
      ],
      targetAudience: [
        "Chief Strategy Officers & Corporate Planning Heads",
        "Managing Directors & Board Members",
        "Strategic Transformation PMO Leaders",
        "Business Unit Directors & General Managers"
      ],
      prerequisites: [
        "Experience in corporate planning, management, or strategic leadership."
      ],
      certificationDetails: "Certified Strategy Professional Credential issued by Tanfidh Management Consultants.",
      bannerUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1600&auto=format&fit=crop",
      status: "PUBLISHED",
      landingPageEnabled: true,
      trainerName: "Said Al Harthi",
      trainerDesignation: "Managing Consultant & Senior Strategy Advisor",
      trainerBio: "Said Al Harthi guides institutional strategy and performance across Oman and GCC ministries, sovereign entities, and regional enterprises.",
      trainerImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
      trainerCompany: "Tanfidh Management Consultants",
      trainerEmail: "saidalharthy@tanfidh.com",
      trainerPhone: "+968 7178 4454",
      startDate: "2026-10-26",
      endDate: "2026-10-27",
      startTime: "08:30 AM",
      endTime: "04:30 PM",
      numDays: 2,
      duration: "2 Days (08:30–16:30)",
      timezone: "Asia/Muscat (GST, UTC+4)",
      mode: "In-person",
      venueName: "Sheraton Oman Hotel",
      address: "Ruwi High Street, Financial District",
      city: "Muscat",
      country: "Sultanate of Oman",
      mapUrl: "https://maps.google.com/?q=Sheraton+Oman+Hotel+Muscat",
      maxSeats: 30,
      availableSeats: 26,
      reservedSeats: 0,
      confirmedSeats: 0,
      waitingList: 0,
      standardPrice: 500,
      currency: "OMR",
      taxPercent: 0,
      vatPercent: 5,
      paymentTerms: "Direct Bank Transfer / Wire",
      offerType: "BOGO",
      offerTitle: "Pay for 1 seat, get 1 seat FREE (Buy 1 Get 1 Free)",
      offerDescription: "Register for 1 paid delegate and bring a colleague or team member at ZERO additional cost. Includes materials, 5-star lunches, and two individual credentials.",
      discountAmount: 500,
      whatsappNumber: "+96871784454",
      keyword: "STRATEGY",
      botFlowId: FLOW_ID,
      autoConfirmation: true,
      autoCertificate: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "course_kpi_pro_2026",
      courseId: "KPI-2026-OM",
      tenantId: TENANT_ID,
      slug: "ai-powered-certified-kpi-professional",
      name: "AI-Powered Certified KPI Professional",
      shortTitle: "Certified KPI Professional with AI",
      category: "Performance Measurement & Analytics",
      type: "Certification",
      description: "Apply the Certified KPI Professional methodology with responsible AI support for KPI discovery, documentation, target setting, data validation, and automated executive reporting.",
      learningObjectives: [
        "Differentiate operational indicators from true Key Performance Indicators (KPIs)",
        "Leverage AI prompts to critique candidate KPIs, draft documentation, and detect measurement pitfalls",
        "Set evidence-based targets and calculate baseline data distributions",
        "Design executive performance dashboards and automated reporting routines",
        "Foster a corporate culture of accountability and performance transparency"
      ],
      highlights: [
        "3 Full Days of Executive Masterclass & Hands-on Lab (08:30–16:30)",
        "Certified KPI Professional Credential with QR Verification",
        "Comprehensive KPI Dictionary & Scorecard Toolkit",
        "Sheraton 5-Star Gourmet Lunch & Executive Networking",
        "Special Offer: Pay for 1 seat and get 1 seat 100% FREE (BOGO)"
      ],
      targetAudience: [
        "KPI Owners & Performance Specialists",
        "M&E (Monitoring & Evaluation) Managers",
        "Data Analysts & BI Professionals",
        "Department Heads & Operational Directors"
      ],
      prerequisites: [
        "Familiarity with organizational performance or reporting."
      ],
      certificationDetails: "Certified KPI Professional Credential issued by Tanfidh Management Consultants.",
      bannerUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1600&auto=format&fit=crop",
      status: "PUBLISHED",
      landingPageEnabled: true,
      trainerName: "Said Al Harthi",
      trainerDesignation: "Managing Consultant & Senior Strategy Advisor",
      trainerBio: "Said Al Harthi specializes in institutional KPI cascading and performance analytics architecture across government and corporate entities.",
      trainerImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
      trainerCompany: "Tanfidh Management Consultants",
      trainerEmail: "saidalharthy@tanfidh.com",
      trainerPhone: "+968 7178 4454",
      startDate: "2026-11-15",
      endDate: "2026-11-17",
      startTime: "08:30 AM",
      endTime: "04:30 PM",
      numDays: 3,
      duration: "3 Days (08:30–16:30)",
      timezone: "Asia/Muscat (GST, UTC+4)",
      mode: "In-person",
      venueName: "Sheraton Oman Hotel",
      address: "Ruwi High Street, Financial District",
      city: "Muscat",
      country: "Sultanate of Oman",
      mapUrl: "https://maps.google.com/?q=Sheraton+Oman+Hotel+Muscat",
      maxSeats: 30,
      availableSeats: 26,
      reservedSeats: 0,
      confirmedSeats: 0,
      waitingList: 0,
      standardPrice: 750,
      currency: "OMR",
      taxPercent: 0,
      vatPercent: 5,
      paymentTerms: "Direct Bank Transfer / Wire",
      offerType: "BOGO",
      offerTitle: "Pay for 1 seat, get 1 seat FREE (Buy 1 Get 1 Free)",
      offerDescription: "Register for 1 paid delegate and bring a colleague or team member at ZERO additional cost. Includes all 3-day materials, 5-star lunches, and two individual credentials.",
      discountAmount: 750,
      whatsappNumber: "+96871784454",
      keyword: "KPI",
      botFlowId: FLOW_ID,
      autoConfirmation: true,
      autoCertificate: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "course_perf_mgmt_pro_2026",
      courseId: "PMP-2026-OM",
      tenantId: TENANT_ID,
      slug: "ai-powered-certified-performance-management-professional",
      name: "AI-Powered Certified Performance Management Professional",
      shortTitle: "Performance Management Professional with AI",
      category: "Performance Architecture & Operations",
      type: "Certification",
      description: "Design and implement comprehensive performance management systems that bridge strategy, individual performance contracts, evaluation cycles, and automated performance reviews with AI.",
      learningObjectives: [
        "Architect end-to-end organizational performance management frameworks",
        "Align individual appraisal contracts with organizational strategic priorities",
        "Conduct constructive performance appraisals and corrective coaching sessions",
        "Use AI tools to draft objective performance feedback and identify performance outliers",
        "Establish fair evaluation routines, moderation panels, and performance governance"
      ],
      highlights: [
        "2 Full Days of Executive Performance Architecture (08:30–16:30)",
        "Certified Performance Management Professional Credential with QR Code",
        "Appraisal Rubrics, Coaching Guides & Performance Review Templates",
        "Sheraton 5-Star Gourmet Lunch & Executive Networking",
        "Special Offer: Pay for 1 seat and get 1 seat 100% FREE (BOGO)"
      ],
      targetAudience: [
        "HR Directors & Head of People Operations",
        "Corporate Performance Managers & Analysts",
        "Operations Directors & Division Chiefs",
        "Organizational Development Leaders"
      ],
      prerequisites: [
        "Background in management, human capital, or operations."
      ],
      certificationDetails: "Certified Performance Management Professional Credential issued by Tanfidh Management Consultants.",
      bannerUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1600&auto=format&fit=crop",
      status: "PUBLISHED",
      landingPageEnabled: true,
      trainerName: "Said Al Harthi",
      trainerDesignation: "Managing Consultant & Senior Strategy Advisor",
      trainerBio: "Said Al Harthi has designed institutional appraisal systems and performance contracts for major ministries, energy operators, and banking institutions.",
      trainerImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
      trainerCompany: "Tanfidh Management Consultants",
      trainerEmail: "saidalharthy@tanfidh.com",
      trainerPhone: "+968 7178 4454",
      startDate: "2026-10-19",
      endDate: "2026-10-20",
      startTime: "08:30 AM",
      endTime: "04:30 PM",
      numDays: 2,
      duration: "2 Days (08:30–16:30)",
      timezone: "Asia/Muscat (GST, UTC+4)",
      mode: "In-person",
      venueName: "Sheraton Oman Hotel",
      address: "Ruwi High Street, Financial District",
      city: "Muscat",
      country: "Sultanate of Oman",
      mapUrl: "https://maps.google.com/?q=Sheraton+Oman+Hotel+Muscat",
      maxSeats: 30,
      availableSeats: 26,
      reservedSeats: 0,
      confirmedSeats: 0,
      waitingList: 0,
      standardPrice: 500,
      currency: "OMR",
      taxPercent: 0,
      vatPercent: 5,
      paymentTerms: "Direct Bank Transfer / Wire",
      offerType: "BOGO",
      offerTitle: "Pay for 1 seat, get 1 seat FREE (Buy 1 Get 1 Free)",
      offerDescription: "Register for 1 paid delegate and bring a colleague or team member at ZERO additional cost. Includes all materials, 5-star lunches, and two individual credentials.",
      discountAmount: 500,
      whatsappNumber: "+96871784454",
      keyword: "PERFORMANCE",
      botFlowId: FLOW_ID,
      autoConfirmation: true,
      autoCertificate: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "course_strategy_exec_pro_2026",
      courseId: "SEP-2026-OM",
      tenantId: TENANT_ID,
      slug: "ai-powered-strategy-execution-professional",
      name: "AI-Powered Certified Strategy Execution Professional",
      shortTitle: "Strategy Execution Professional with AI",
      category: "Execution & Transformation",
      type: "Certification",
      description: "Close the execution gap between high-level strategy and frontline delivery. Learn how to sequence initiatives, unblock critical path bottlenecks, and govern execution using AI-enabled PMO frameworks.",
      learningObjectives: [
        "Translate strategic objectives into prioritized, actionable portfolio initiatives",
        "Apply agile execution cadences (OKR check-ins, sprint milestones) alongside classical PMO governance",
        "Use AI to forecast initiative delays, dependencies, and resource constraints",
        "Manage change resistance and maintain multi-stakeholder momentum",
        "Deliver verifiable executive impact dashboards for steering committees and board reviews"
      ],
      highlights: [
        "2 Full Days of Executive Execution Masterclass (08:30–16:30)",
        "Certified Strategy Execution Professional Credential with QR Code",
        "Initiative Charters, Critical Path Calculators & Risk Heatmaps",
        "Sheraton 5-Star Gourmet Lunch & Executive Networking",
        "Special Offer: Pay for 1 seat and get 1 seat 100% FREE (BOGO)"
      ],
      targetAudience: [
        "Chief Operating Officers & Operations Leaders",
        "PMO Directors & Portfolio Program Managers",
        "Transformation & Change Management Heads",
        "Senior Project Managers & Department Chiefs"
      ],
      prerequisites: [
        "Experience in project, program, or organizational management."
      ],
      certificationDetails: "Certified Strategy Execution Professional Credential issued by Tanfidh Management Consultants.",
      bannerUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=1600&auto=format&fit=crop",
      status: "PUBLISHED",
      landingPageEnabled: true,
      trainerName: "Said Al Harthi",
      trainerDesignation: "Managing Consultant & Senior Strategy Advisor",
      trainerBio: "Said Al Harthi has directed major national and corporate strategic execution programs across Oman and the GCC.",
      trainerImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
      trainerCompany: "Tanfidh Management Consultants",
      trainerEmail: "saidalharthy@tanfidh.com",
      trainerPhone: "+968 7178 4454",
      startDate: "2026-11-09",
      endDate: "2026-11-10",
      startTime: "08:30 AM",
      endTime: "04:30 PM",
      numDays: 2,
      duration: "2 Days (08:30–16:30)",
      timezone: "Asia/Muscat (GST, UTC+4)",
      mode: "In-person",
      venueName: "Sheraton Oman Hotel",
      address: "Ruwi High Street, Financial District",
      city: "Muscat",
      country: "Sultanate of Oman",
      mapUrl: "https://maps.google.com/?q=Sheraton+Oman+Hotel+Muscat",
      maxSeats: 30,
      availableSeats: 26,
      reservedSeats: 0,
      confirmedSeats: 0,
      waitingList: 0,
      standardPrice: 500,
      currency: "OMR",
      taxPercent: 0,
      vatPercent: 5,
      paymentTerms: "Direct Bank Transfer / Wire",
      offerType: "BOGO",
      offerTitle: "Pay for 1 seat, get 1 seat FREE (Buy 1 Get 1 Free)",
      offerDescription: "Register for 1 paid delegate and bring a colleague or team member at ZERO additional cost. Includes all materials, 5-star lunches, and two individual credentials.",
      discountAmount: 500,
      whatsappNumber: "+96871784454",
      keyword: "EXECUTION",
      botFlowId: FLOW_ID,
      autoConfirmation: true,
      autoCertificate: true,
      createdAt: now,
      updatedAt: now,
    }
  ]

  await db.systemSetting.upsert({
    where: { tenantId_key: { tenantId: TENANT_ID, key: "training_course_catalog" } },
    update: { value: JSON.stringify(courses), type: "JSON", category: "TRAINING" },
    create: { tenantId: TENANT_ID, key: "training_course_catalog", value: JSON.stringify(courses), type: "JSON", category: "TRAINING" },
  })
  console.log(`✓ Seeded ${courses.length} published courses into training_course_catalog for Tanfidh!`)
}

main().catch(err => {
  console.error("Seed script failed:", err)
  process.exit(1)
})
