export interface VCardTemplate {
  id: string
  name: string
  tagline: string
  description: string
  previewColors: string[]
  theme: "light" | "dark" | "custom"
  wrapperClass: string
  cardClass: string
  headerBg: string
  headerOverlay: string
  avatarBorder: string
  titleClass: string
  subtitleClass: string
  badgeClass: string
  sectionTitleClass: string
  primaryButtonClass: string
  secondaryButtonClass: string
  actionButtonClass: {
    whatsapp: string
    call: string
    vcf: string
    directions: string
  }
  serviceCardClass: string
  footerClass: string
}

export const VCARD_TEMPLATES: Record<string, VCardTemplate> = {
  modern: {
    id: "modern",
    name: "Modern Minimal",
    tagline: "Clean & Contemporary",
    description: "Refined slate surface with crisp typography, soft elevations, and airy spacing. Perfect for corporate & tech.",
    previewColors: ["#0f766e", "#0284c7", "#f8fafc"],
    theme: "light",
    wrapperClass: "bg-gradient-to-br from-slate-100 via-slate-50 to-slate-200 text-slate-800",
    cardClass: "bg-white/95 backdrop-blur-md border border-slate-200/80 shadow-2xl rounded-3xl",
    headerBg: "bg-gradient-to-r from-teal-700 to-teal-900",
    headerOverlay: "bg-gradient-to-b from-black/20 via-transparent to-black/60",
    avatarBorder: "border-4 border-white shadow-xl ring-2 ring-teal-500/20",
    titleClass: "text-slate-900 font-extrabold tracking-tight",
    subtitleClass: "text-slate-600 font-medium",
    badgeClass: "bg-teal-50 text-teal-700 border border-teal-200",
    sectionTitleClass: "text-slate-900 font-bold",
    primaryButtonClass: "bg-gradient-to-r from-teal-600 to-emerald-600 hover:from-teal-700 hover:to-emerald-700 text-white shadow-lg shadow-teal-700/25",
    secondaryButtonClass: "bg-slate-900 hover:bg-slate-800 text-white shadow-md",
    actionButtonClass: {
      whatsapp: "bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border-emerald-200/80",
      call: "bg-blue-50 hover:bg-blue-100 text-blue-800 border-blue-200/80",
      vcf: "bg-indigo-50 hover:bg-indigo-100 text-indigo-800 border-indigo-200/80",
      directions: "bg-amber-50 hover:bg-amber-100 text-amber-800 border-amber-200/80",
    },
    serviceCardClass: "bg-slate-50/80 hover:bg-white border border-slate-200/90 text-slate-800 shadow-xs",
    footerClass: "border-t border-slate-200 text-slate-500",
  },

  executive: {
    id: "executive",
    name: "Midnight Executive",
    tagline: "Opulent & Luxurious",
    description: "Deep obsidian black with rich brushed champagne gold foil accents and metallic glass. Built for executives and VIP services.",
    previewColors: ["#09090b", "#d97706", "#f59e0b"],
    theme: "dark",
    wrapperClass: "bg-gradient-to-b from-zinc-950 via-zinc-900 to-black text-zinc-100",
    cardClass: "bg-zinc-900/90 backdrop-blur-xl border border-amber-500/30 shadow-[0_20px_50px_rgba(0,0,0,0.8)] rounded-3xl ring-1 ring-amber-500/20",
    headerBg: "bg-gradient-to-r from-zinc-950 via-amber-950/60 to-zinc-950",
    headerOverlay: "bg-gradient-to-b from-black/40 via-transparent to-zinc-900",
    avatarBorder: "border-4 border-amber-500/80 shadow-2xl shadow-amber-500/20 ring-2 ring-amber-400/40",
    titleClass: "text-amber-100 font-black tracking-tight",
    subtitleClass: "text-amber-300/80 font-medium",
    badgeClass: "bg-amber-950/80 text-amber-300 border border-amber-700/60",
    sectionTitleClass: "text-amber-200 font-bold",
    primaryButtonClass: "bg-gradient-to-r from-amber-500 via-amber-600 to-yellow-600 hover:from-amber-600 hover:to-yellow-700 text-zinc-950 font-black shadow-lg shadow-amber-950/50 border border-amber-400/40",
    secondaryButtonClass: "bg-zinc-800 hover:bg-zinc-700 text-amber-200 border border-amber-600/40 shadow-md",
    actionButtonClass: {
      whatsapp: "bg-zinc-800/90 hover:bg-zinc-700 text-emerald-400 border-emerald-500/30",
      call: "bg-zinc-800/90 hover:bg-zinc-700 text-amber-400 border-amber-500/30",
      vcf: "bg-zinc-800/90 hover:bg-zinc-700 text-indigo-400 border-indigo-500/30",
      directions: "bg-zinc-800/90 hover:bg-zinc-700 text-amber-300 border-amber-500/30",
    },
    serviceCardClass: "bg-zinc-900/80 hover:bg-zinc-800/90 border border-amber-500/25 text-zinc-100 shadow-md",
    footerClass: "border-t border-zinc-800 text-zinc-500",
  },

  emerald: {
    id: "emerald",
    name: "Royal Emerald",
    tagline: "Fizmoh Signature",
    description: "Deep lush forest emerald and vibrant mint. Organic vitality with frosted jade highlights.",
    previewColors: ["#064e3b", "#10b981", "#34d399"],
    theme: "dark",
    wrapperClass: "bg-gradient-to-br from-emerald-950 via-teal-900 to-emerald-900 text-slate-100",
    cardClass: "bg-emerald-950/85 backdrop-blur-xl border border-emerald-500/30 shadow-2xl rounded-3xl",
    headerBg: "bg-gradient-to-r from-emerald-800 via-teal-700 to-emerald-900",
    headerOverlay: "bg-gradient-to-b from-black/30 via-transparent to-emerald-950",
    avatarBorder: "border-4 border-emerald-400 shadow-xl ring-2 ring-mint-400/40",
    titleClass: "text-white font-black tracking-tight",
    subtitleClass: "text-emerald-200 font-medium",
    badgeClass: "bg-emerald-900/90 text-emerald-300 border border-emerald-500/50",
    sectionTitleClass: "text-emerald-200 font-bold",
    primaryButtonClass: "bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 text-slate-950 font-black shadow-lg shadow-emerald-950/60",
    secondaryButtonClass: "bg-emerald-900/90 hover:bg-emerald-800 text-emerald-200 border border-emerald-600/50",
    actionButtonClass: {
      whatsapp: "bg-emerald-900/60 hover:bg-emerald-800/80 text-emerald-300 border-emerald-500/40",
      call: "bg-teal-900/60 hover:bg-teal-800/80 text-teal-300 border-teal-500/40",
      vcf: "bg-cyan-900/60 hover:bg-cyan-800/80 text-cyan-300 border-cyan-500/40",
      directions: "bg-emerald-900/60 hover:bg-emerald-800/80 text-emerald-200 border-emerald-500/40",
    },
    serviceCardClass: "bg-emerald-900/40 hover:bg-emerald-900/70 border border-emerald-600/30 text-emerald-50 shadow-md",
    footerClass: "border-t border-emerald-800/60 text-emerald-400/70",
  },

  sunset: {
    id: "sunset",
    name: "Sunset Horizon",
    tagline: "Vibrant & Warm Energy",
    description: "Radiant rose, coral, and tangerine gradients. Exudes high energy, creativity, and lifestyle appeal.",
    previewColors: ["#f43f5e", "#f97316", "#fbbf24"],
    theme: "light",
    wrapperClass: "bg-gradient-to-br from-rose-100 via-orange-50 to-amber-100 text-slate-800",
    cardClass: "bg-white/95 backdrop-blur-md border border-orange-200/80 shadow-2xl rounded-3xl",
    headerBg: "bg-gradient-to-r from-rose-500 via-pink-600 to-orange-500",
    headerOverlay: "bg-gradient-to-b from-black/20 via-transparent to-black/60",
    avatarBorder: "border-4 border-white shadow-xl ring-2 ring-rose-500/30",
    titleClass: "text-slate-900 font-black tracking-tight",
    subtitleClass: "text-rose-700 font-semibold",
    badgeClass: "bg-rose-50 text-rose-700 border border-rose-200",
    sectionTitleClass: "text-slate-900 font-bold",
    primaryButtonClass: "bg-gradient-to-r from-rose-500 to-orange-500 hover:from-rose-600 hover:to-orange-600 text-white font-bold shadow-lg shadow-rose-500/30",
    secondaryButtonClass: "bg-slate-900 hover:bg-slate-800 text-white shadow-md",
    actionButtonClass: {
      whatsapp: "bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border-emerald-200/80",
      call: "bg-rose-50 hover:bg-rose-100 text-rose-800 border-rose-200/80",
      vcf: "bg-orange-50 hover:bg-orange-100 text-orange-800 border-orange-200/80",
      directions: "bg-amber-50 hover:bg-amber-100 text-amber-800 border-amber-200/80",
    },
    serviceCardClass: "bg-orange-50/40 hover:bg-white border border-orange-200/70 text-slate-800 shadow-xs",
    footerClass: "border-t border-orange-200/60 text-slate-500",
  },

  ocean: {
    id: "ocean",
    name: "Pacific Cobalt",
    tagline: "Fintech & High-Tech Blue",
    description: "Deep sapphire navy with electric royal blue and sharp cyan highlights. Conveys trust, security, and precision.",
    previewColors: ["#1e3a8a", "#0284c7", "#38bdf8"],
    theme: "dark",
    wrapperClass: "bg-gradient-to-b from-slate-950 via-blue-950 to-slate-900 text-slate-100",
    cardClass: "bg-slate-900/90 backdrop-blur-xl border border-blue-500/30 shadow-2xl rounded-3xl ring-1 ring-blue-500/20",
    headerBg: "bg-gradient-to-r from-blue-900 via-indigo-900 to-slate-950",
    headerOverlay: "bg-gradient-to-b from-black/30 via-transparent to-slate-900",
    avatarBorder: "border-4 border-blue-500 shadow-xl ring-2 ring-cyan-400/40",
    titleClass: "text-white font-black tracking-tight",
    subtitleClass: "text-blue-300 font-medium",
    badgeClass: "bg-blue-950/80 text-blue-300 border border-blue-700/50",
    sectionTitleClass: "text-blue-200 font-bold",
    primaryButtonClass: "bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700 text-white font-bold shadow-lg shadow-blue-950/60",
    secondaryButtonClass: "bg-slate-800 hover:bg-slate-700 text-blue-200 border border-blue-500/30 shadow-md",
    actionButtonClass: {
      whatsapp: "bg-slate-800/80 hover:bg-slate-700 text-emerald-400 border-emerald-500/30",
      call: "bg-slate-800/80 hover:bg-slate-700 text-blue-400 border-blue-500/30",
      vcf: "bg-slate-800/80 hover:bg-slate-700 text-cyan-400 border-cyan-500/30",
      directions: "bg-slate-800/80 hover:bg-slate-700 text-indigo-300 border-indigo-500/30",
    },
    serviceCardClass: "bg-slate-900/70 hover:bg-slate-800/90 border border-blue-500/20 text-slate-100 shadow-md",
    footerClass: "border-t border-slate-800 text-slate-500",
  },

  cyber: {
    id: "cyber",
    name: "Cyberpunk Neon",
    tagline: "Futuristic & Matrix Glow",
    description: "Ultra-dark void black with neon violet, laser cyan, and hot magenta glowing borders. For creatives, gaming, and innovators.",
    previewColors: ["#090514", "#8b5cf6", "#06b6d4"],
    theme: "dark",
    wrapperClass: "bg-[#07050e] text-purple-100",
    cardClass: "bg-[#0e0a1f]/90 backdrop-blur-xl border-2 border-purple-500/40 shadow-[0_0_50px_rgba(139,92,246,0.25)] rounded-3xl",
    headerBg: "bg-gradient-to-r from-purple-900 via-violet-800 to-indigo-950",
    headerOverlay: "bg-gradient-to-b from-black/40 via-transparent to-[#0e0a1f]",
    avatarBorder: "border-4 border-cyan-400 shadow-[0_0_20px_rgba(6,182,212,0.6)] ring-2 ring-purple-400",
    titleClass: "text-transparent bg-clip-text bg-gradient-to-r from-cyan-300 via-purple-300 to-pink-300 font-black tracking-tight",
    subtitleClass: "text-cyan-400 font-mono text-xs",
    badgeClass: "bg-purple-950/90 text-cyan-300 border border-cyan-500/50 font-mono",
    sectionTitleClass: "text-cyan-300 font-mono font-bold uppercase tracking-wider",
    primaryButtonClass: "bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-400 hover:to-purple-500 text-slate-950 font-black shadow-[0_0_25px_rgba(6,182,212,0.4)]",
    secondaryButtonClass: "bg-[#181236] hover:bg-[#20184a] text-purple-200 border border-purple-500/50 shadow-md",
    actionButtonClass: {
      whatsapp: "bg-[#161131] hover:bg-[#201945] text-emerald-400 border-emerald-500/40",
      call: "bg-[#161131] hover:bg-[#201945] text-cyan-400 border-cyan-500/40",
      vcf: "bg-[#161131] hover:bg-[#201945] text-purple-400 border-purple-500/40",
      directions: "bg-[#161131] hover:bg-[#201945] text-pink-400 border-pink-500/40",
    },
    serviceCardClass: "bg-[#140e2b] hover:bg-[#1b133b] border border-purple-500/30 text-purple-100 shadow-md",
    footerClass: "border-t border-purple-950 text-purple-400/60",
  },

  boutique: {
    id: "boutique",
    name: "Pastel Chic",
    tagline: "French Elegance & Boutique",
    description: "Warm linen cream with soft blush rose and elegant serif titles. Tailored for salons, spas, boutique fashion, and luxury dining.",
    previewColors: ["#fff7ed", "#f43f5e", "#fda4af"],
    theme: "light",
    wrapperClass: "bg-[#fdfaf7] text-stone-800 font-serif",
    cardClass: "bg-[#fffdfa] border border-stone-200/90 shadow-xl rounded-3xl",
    headerBg: "bg-gradient-to-r from-rose-300 via-amber-200 to-rose-200",
    headerOverlay: "bg-gradient-to-b from-black/10 via-transparent to-[#fffdfa]",
    avatarBorder: "border-4 border-[#fffdfa] shadow-lg ring-2 ring-rose-300/60",
    titleClass: "text-stone-900 font-serif font-black tracking-wide",
    subtitleClass: "text-stone-600 font-sans italic text-xs",
    badgeClass: "bg-rose-50 text-rose-800 border border-rose-200 font-sans",
    sectionTitleClass: "text-stone-900 font-serif font-bold",
    primaryButtonClass: "bg-stone-900 hover:bg-stone-800 text-[#fffdfa] font-sans font-bold shadow-md",
    secondaryButtonClass: "bg-rose-100 hover:bg-rose-200 text-rose-900 border border-rose-300/60 font-sans font-semibold",
    actionButtonClass: {
      whatsapp: "bg-[#f8f5f0] hover:bg-rose-50 text-emerald-800 border-stone-200",
      call: "bg-[#f8f5f0] hover:bg-rose-50 text-rose-900 border-stone-200",
      vcf: "bg-[#f8f5f0] hover:bg-rose-50 text-stone-800 border-stone-200",
      directions: "bg-[#f8f5f0] hover:bg-rose-50 text-amber-900 border-stone-200",
    },
    serviceCardClass: "bg-[#fbf8f4] hover:bg-white border border-stone-200 text-stone-800 shadow-2xs font-sans",
    footerClass: "border-t border-stone-200 text-stone-400 font-sans",
  },

  frost: {
    id: "frost",
    name: "Frosted Glass",
    tagline: "Apple Glassmorphism",
    description: "Ultra-modern multi-layered frosted glass with delicate iridescent border reflections and heavy backdrop blur.",
    previewColors: ["#e0f2fe", "#38bdf8", "#818cf8"],
    theme: "light",
    wrapperClass: "bg-gradient-to-tr from-sky-100 via-indigo-50 to-purple-100 text-slate-800",
    cardClass: "bg-white/60 backdrop-blur-2xl border border-white/60 shadow-[0_20px_60px_rgba(0,0,0,0.08)] rounded-3xl ring-1 ring-white/80",
    headerBg: "bg-gradient-to-r from-sky-400/80 via-blue-500/70 to-indigo-500/80 backdrop-blur-md",
    headerOverlay: "bg-gradient-to-b from-white/10 via-transparent to-white/40",
    avatarBorder: "border-4 border-white/90 shadow-2xl backdrop-blur-md ring-2 ring-sky-300/50",
    titleClass: "text-slate-900 font-black tracking-tight",
    subtitleClass: "text-slate-600 font-semibold",
    badgeClass: "bg-white/80 backdrop-blur-md text-sky-800 border border-sky-200/80",
    sectionTitleClass: "text-slate-900 font-bold",
    primaryButtonClass: "bg-gradient-to-r from-sky-600 via-blue-600 to-indigo-600 hover:from-sky-700 hover:to-indigo-700 text-white font-bold shadow-lg shadow-sky-600/20 backdrop-blur-md",
    secondaryButtonClass: "bg-white/80 hover:bg-white text-slate-800 border border-slate-200 shadow-md backdrop-blur-md",
    actionButtonClass: {
      whatsapp: "bg-white/70 hover:bg-white/90 text-emerald-800 border-white/80 backdrop-blur-md",
      call: "bg-white/70 hover:bg-white/90 text-sky-800 border-white/80 backdrop-blur-md",
      vcf: "bg-white/70 hover:bg-white/90 text-indigo-800 border-white/80 backdrop-blur-md",
      directions: "bg-white/70 hover:bg-white/90 text-amber-800 border-white/80 backdrop-blur-md",
    },
    serviceCardClass: "bg-white/50 hover:bg-white/80 backdrop-blur-md border border-white/80 text-slate-800 shadow-xs",
    footerClass: "border-t border-white/60 text-slate-500",
  },

  artisan: {
    id: "artisan",
    name: "Artisan Craft",
    tagline: "Coffee, Wood & Terracotta",
    description: "Roasted espresso bronze, warm terracotta and sand tones. Perfect for cafes, bakeries, artisan workshops, and design studios.",
    previewColors: ["#451a03", "#b45309", "#d97706"],
    theme: "light",
    wrapperClass: "bg-[#f5ede4] text-[#3e271a]",
    cardClass: "bg-[#fdfaf6] border border-[#e4d6c7] shadow-xl rounded-3xl",
    headerBg: "bg-gradient-to-r from-[#451a03] via-[#78350f] to-[#92400e]",
    headerOverlay: "bg-gradient-to-b from-black/25 via-transparent to-[#fdfaf6]",
    avatarBorder: "border-4 border-[#fdfaf6] shadow-xl ring-2 ring-[#b45309]/30",
    titleClass: "text-[#2b170c] font-black tracking-tight",
    subtitleClass: "text-[#78350f] font-semibold text-xs",
    badgeClass: "bg-[#ede2d5] text-[#5e2f10] border border-[#dbc6b2]",
    sectionTitleClass: "text-[#2b170c] font-bold",
    primaryButtonClass: "bg-gradient-to-r from-[#78350f] to-[#b45309] hover:from-[#5e2a0b] hover:to-[#92400e] text-amber-50 font-bold shadow-lg shadow-[#451a03]/30",
    secondaryButtonClass: "bg-[#3e271a] hover:bg-[#2b170c] text-amber-100 shadow-md",
    actionButtonClass: {
      whatsapp: "bg-[#f2e6d8] hover:bg-[#e9d9c6] text-emerald-900 border-[#dccebf]",
      call: "bg-[#f2e6d8] hover:bg-[#e9d9c6] text-[#78350f] border-[#dccebf]",
      vcf: "bg-[#f2e6d8] hover:bg-[#e9d9c6] text-[#5e2a0b] border-[#dccebf]",
      directions: "bg-[#f2e6d8] hover:bg-[#e9d9c6] text-[#92400e] border-[#dccebf]",
    },
    serviceCardClass: "bg-[#f7efe5] hover:bg-white border border-[#e2d2c1] text-[#3e271a] shadow-2xs",
    footerClass: "border-t border-[#e2d2c1] text-[#8c6751]",
  },

  brutalist: {
    id: "brutalist",
    name: "Neo-Brutalist",
    tagline: "Bold Swiss High-Contrast",
    description: "Stark monochrome with bold 2.5px borders, vivid neon yellow highlight chips, and punchy modern typography.",
    previewColors: ["#000000", "#facc15", "#ffffff"],
    theme: "light",
    wrapperClass: "bg-[#f4f4f5] text-black",
    cardClass: "bg-white border-3 border-black shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] rounded-2xl",
    headerBg: "bg-black",
    headerOverlay: "bg-gradient-to-b from-transparent via-transparent to-black/80",
    avatarBorder: "border-3 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] ring-2 ring-yellow-400",
    titleClass: "text-black font-black tracking-tight uppercase text-xl",
    subtitleClass: "text-black/80 font-bold text-xs uppercase tracking-wider",
    badgeClass: "bg-yellow-300 text-black border-2 border-black font-bold uppercase text-[10px]",
    sectionTitleClass: "text-black font-black uppercase tracking-tight",
    primaryButtonClass: "bg-yellow-400 hover:bg-yellow-300 text-black font-black border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] active:translate-x-0.5 active:translate-y-0.5 active:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]",
    secondaryButtonClass: "bg-black hover:bg-zinc-800 text-white font-bold border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]",
    actionButtonClass: {
      whatsapp: "bg-emerald-300 hover:bg-emerald-200 text-black border-2 border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]",
      call: "bg-sky-300 hover:bg-sky-200 text-black border-2 border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]",
      vcf: "bg-purple-300 hover:bg-purple-200 text-black border-2 border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]",
      directions: "bg-orange-300 hover:bg-orange-200 text-black border-2 border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]",
    },
    serviceCardClass: "bg-white hover:bg-yellow-50 border-2 border-black text-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]",
    footerClass: "border-t-2 border-black text-black/70 font-mono text-xs",
  },

  "curve-emerald": {
    id: "curve-emerald",
    name: "Executive Curve",
    tagline: "Forest Emerald & Architectural Arch",
    description: "Signature organic curved hero wave with deep forest emerald accents, clean white surface, and executive chevron info tiles (David Okello style).",
    previewColors: ["#14532d", "#15803d", "#f0fdf4"],
    theme: "light",
    wrapperClass: "bg-gradient-to-br from-slate-100 via-stone-50 to-emerald-50 text-slate-800",
    cardClass: "bg-white border border-emerald-950/10 shadow-2xl rounded-3xl overflow-hidden",
    headerBg: "bg-gradient-to-b from-emerald-950 via-emerald-900 to-emerald-800",
    headerOverlay: "bg-gradient-to-t from-black/40 via-transparent to-transparent",
    avatarBorder: "border-4 border-white shadow-xl ring-2 ring-emerald-700/30",
    titleClass: "text-emerald-950 font-black tracking-tight text-xl uppercase",
    subtitleClass: "text-emerald-700 font-semibold text-xs tracking-wide",
    badgeClass: "bg-emerald-50 text-emerald-800 border border-emerald-200 font-bold",
    sectionTitleClass: "text-emerald-950 font-black tracking-tight",
    primaryButtonClass: "bg-emerald-800 hover:bg-emerald-900 text-white font-bold shadow-md shadow-emerald-900/20",
    secondaryButtonClass: "bg-white hover:bg-emerald-50 text-emerald-900 border-2 border-emerald-800 font-bold",
    actionButtonClass: {
      whatsapp: "bg-emerald-800 hover:bg-emerald-900 text-white border-transparent",
      call: "bg-emerald-800 hover:bg-emerald-900 text-white border-transparent",
      vcf: "bg-emerald-900 hover:bg-emerald-950 text-white border-transparent",
      directions: "bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border-emerald-200",
    },
    serviceCardClass: "bg-emerald-950 text-white hover:bg-emerald-900 border border-emerald-800 shadow-md",
    footerClass: "border-t border-emerald-100 text-emerald-800/70 text-xs",
  },

  "midnight-navy": {
    id: "midnight-navy",
    name: "Midnight Navy & Amber",
    tagline: "Deep Sapphire & Warm Gold",
    description: "Sleek dark sapphire card with rich amber gold glowing accents, quote box, and high-contrast call/email actions (Farida Mwaniki style).",
    previewColors: ["#0f172a", "#d97706", "#1e293b"],
    theme: "dark",
    wrapperClass: "bg-[#0b1120] text-slate-100",
    cardClass: "bg-[#111827] border border-amber-500/20 shadow-2xl rounded-3xl overflow-hidden",
    headerBg: "bg-gradient-to-b from-[#0f172a] via-[#1e293b] to-[#111827]",
    headerOverlay: "bg-gradient-to-t from-[#111827] via-transparent to-black/40",
    avatarBorder: "border-4 border-amber-500/40 shadow-xl ring-4 ring-amber-500/20",
    titleClass: "text-amber-400 font-black tracking-wider text-xl uppercase",
    subtitleClass: "text-slate-300 font-semibold text-xs tracking-wide",
    badgeClass: "bg-amber-500/10 text-amber-300 border border-amber-500/30 font-bold",
    sectionTitleClass: "text-amber-400 font-bold tracking-wide",
    primaryButtonClass: "bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-slate-950 font-black shadow-lg shadow-amber-500/20",
    secondaryButtonClass: "bg-slate-800 hover:bg-slate-700 text-white border border-slate-700 font-bold",
    actionButtonClass: {
      whatsapp: "bg-amber-500 hover:bg-amber-600 text-slate-950 border-amber-400 font-bold",
      call: "bg-gradient-to-r from-amber-600 to-orange-600 text-white border-transparent font-bold",
      vcf: "bg-slate-800 hover:bg-slate-700 text-amber-400 border border-amber-500/30",
      directions: "bg-slate-800/80 hover:bg-slate-800 text-slate-200 border-slate-700",
    },
    serviceCardClass: "bg-slate-800/90 hover:bg-slate-800 border border-slate-700/80 text-white shadow-md",
    footerClass: "border-t border-slate-800 text-slate-400 text-xs",
  },

  "champagne-gold": {
    id: "champagne-gold",
    name: "Champagne Luxury",
    tagline: "Ivory Cream & Brushed Gold",
    description: "Warm ivory and champagne minimalist elegance with brushed gold halo avatar ring and deep forest emerald action buttons (Aisha Abdullahi style).",
    previewColors: ["#fef3c7", "#b45309", "#064e3b"],
    theme: "light",
    wrapperClass: "bg-gradient-to-br from-[#fbf8f3] via-[#f7f2e9] to-[#eee5d5] text-stone-800",
    cardClass: "bg-[#fffdfa] border border-[#e8ded0] shadow-2xl rounded-3xl overflow-hidden",
    headerBg: "bg-gradient-to-b from-[#f2e7d5] via-[#faefe0] to-[#fffdfa]",
    headerOverlay: "bg-gradient-to-t from-[#fffdfa] via-transparent to-transparent",
    avatarBorder: "border-4 border-[#d4af37] shadow-xl ring-4 ring-[#d4af37]/20",
    titleClass: "text-[#92400e] font-black tracking-widest text-xl uppercase",
    subtitleClass: "text-stone-600 font-medium text-xs tracking-wider",
    badgeClass: "bg-[#fef3c7] text-[#92400e] border border-[#fde68a] font-bold",
    sectionTitleClass: "text-[#92400e] font-bold tracking-wide",
    primaryButtonClass: "bg-[#b45309] hover:bg-[#92400e] text-white font-bold shadow-md shadow-[#b45309]/20",
    secondaryButtonClass: "bg-[#064e3b] hover:bg-[#065f46] text-white font-bold",
    actionButtonClass: {
      whatsapp: "bg-[#064e3b] hover:bg-[#065f46] text-white border-transparent",
      call: "bg-[#d97706] hover:bg-[#b45309] text-white border-transparent",
      vcf: "bg-[#b45309] hover:bg-[#92400e] text-white border-transparent",
      directions: "bg-[#fef3c7] hover:bg-[#fde68a] text-[#92400e] border-[#fde68a]",
    },
    serviceCardClass: "bg-[#f9f5ee] hover:bg-white border border-[#e6dbc9] text-stone-800 shadow-xs",
    footerClass: "border-t border-[#ede3d3] text-stone-500 text-xs",
  },
}

export function getVCardTemplate(templateId?: string | null): VCardTemplate {
  if (!templateId) return VCARD_TEMPLATES.modern
  return VCARD_TEMPLATES[templateId.toLowerCase()] || VCARD_TEMPLATES.modern
}

export const TEMPLATE_LIST = Object.values(VCARD_TEMPLATES)
